name: Deploy GitHub Pages with Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Generate Sitemap
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
        echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
        echo '<url><loc>https://codebloodedmama.github.io/AFE_exam/q07/</loc><priority>1.0</priority></url>' >> sitemap.xml
        echo '<url><loc>https://codebloodedmama.github.io/AFE_exam/q07/login</loc><priority>0.9</priority></url>' >> sitemap.xml
        echo '<url><loc>https://codebloodedmama.github.io/AFE_exam/q07/dashboard</loc><priority>0.8</priority></url>' >> sitemap.xml
        echo '</urlset>' >> sitemap.xml

    - name: Build Project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out